Traceback (most recent call last):
  File "C:\Users\40020507\Downloads\diagslave-3.4\win\test1.py", line 4, in <module>
    instrument = minimalmodbus.Instrument('127.0.0.1', 5020)  # Adjust IP and port as needed
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\minimalmodbus.py", line 225, in __init__
    self.serial = _serialports[port] = serial.Serial(
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port '127.0.0.1': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
